/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WhisperAudioPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/recorder.ts
var AudioRecorder = class {
  constructor(app) {
    this.app = app;
    this.mediaRecorder = null;
    this.stream = null;
    this.audioChunks = [];
    this.timerInterval = null;
    this.currentChunkSizeBytes = 0;
    this.maxChunkSizeBytes = 22 * 1024 * 1024;
    // 22MB for safety margin
    this.recordedBlobs = [];
    this.isRecording = false;
    this.isPaused = false;
    this.duration = 0;
    this.onTick = () => {
    };
    this.onStateChange = () => {
    };
  }
  getSupportedMimeType() {
    const types = [
      "audio/webm;codecs=opus",
      "audio/webm",
      "audio/ogg;codecs=opus",
      "audio/mp4",
      "audio/aac",
      "audio/mpeg"
    ];
    for (const type of types) {
      if (MediaRecorder.isTypeSupported(type)) {
        return type;
      }
    }
    return "";
  }
  getExtensionFromMimeType(mimeType) {
    if (mimeType.includes("webm"))
      return "webm";
    if (mimeType.includes("ogg"))
      return "ogg";
    if (mimeType.includes("mp4") || mimeType.includes("aac"))
      return "m4a";
    if (mimeType.includes("mpeg"))
      return "mp3";
    return "webm";
  }
  async start(deviceId = "default", maxChunkSizeBytes = 22 * 1024 * 1024) {
    this.maxChunkSizeBytes = maxChunkSizeBytes;
    const constraints = {
      audio: deviceId === "default" ? true : { deviceId: { exact: deviceId } }
    };
    this.stream = await navigator.mediaDevices.getUserMedia(constraints);
    const mimeType = this.getSupportedMimeType();
    const options = mimeType ? { mimeType } : void 0;
    this.mediaRecorder = new MediaRecorder(this.stream, options);
    this.audioChunks = [];
    this.recordedBlobs = [];
    this.currentChunkSizeBytes = 0;
    this.duration = 0;
    this.mediaRecorder.ondataavailable = (event) => {
      if (event.data && event.data.size > 0) {
        this.audioChunks.push(event.data);
        this.currentChunkSizeBytes += event.data.size;
        if (this.currentChunkSizeBytes >= this.maxChunkSizeBytes) {
          this.rolloverChunk();
        }
      }
    };
    this.mediaRecorder.start(250);
    this.isRecording = true;
    this.isPaused = false;
    this.timerInterval = setInterval(() => {
      this.duration += 1;
      this.onTick(this.duration);
    }, 1e3);
    this.onStateChange({ isRecording: this.isRecording, isPaused: this.isPaused });
  }
  async rolloverChunk() {
    if (!this.mediaRecorder || this.mediaRecorder.state !== "recording" || !this.stream) {
      return;
    }
    const oldRecorder = this.mediaRecorder;
    const oldChunks = [...this.audioChunks];
    oldRecorder.ondataavailable = (event) => {
      if (event.data && event.data.size > 0) {
        oldChunks.push(event.data);
      }
    };
    this.audioChunks = [];
    this.currentChunkSizeBytes = 0;
    const mimeType = this.getSupportedMimeType();
    const options = mimeType ? { mimeType } : void 0;
    this.mediaRecorder = new MediaRecorder(this.stream, options);
    this.mediaRecorder.ondataavailable = (event) => {
      if (event.data && event.data.size > 0) {
        this.audioChunks.push(event.data);
        this.currentChunkSizeBytes += event.data.size;
        if (this.currentChunkSizeBytes >= this.maxChunkSizeBytes) {
          this.rolloverChunk();
        }
      }
    };
    this.mediaRecorder.start(250);
    oldRecorder.onstop = () => {
      const finalMime = oldRecorder.mimeType || this.getSupportedMimeType() || "audio/webm";
      const blob = new Blob(oldChunks, { type: finalMime });
      this.recordedBlobs.push(blob);
    };
    oldRecorder.stop();
  }
  pause() {
    if (this.mediaRecorder && this.isRecording && !this.isPaused) {
      this.mediaRecorder.pause();
      this.isPaused = true;
      if (this.timerInterval) {
        clearInterval(this.timerInterval);
        this.timerInterval = null;
      }
      this.onStateChange({ isRecording: this.isRecording, isPaused: this.isPaused });
    }
  }
  resume() {
    if (this.mediaRecorder && this.isRecording && this.isPaused) {
      this.mediaRecorder.resume();
      this.isPaused = false;
      this.timerInterval = setInterval(() => {
        this.duration += 1;
        this.onTick(this.duration);
      }, 1e3);
      this.onStateChange({ isRecording: this.isRecording, isPaused: this.isPaused });
    }
  }
  async stop(targetFolder = "", saveToVault = true) {
    return new Promise((resolve, reject) => {
      if (!this.mediaRecorder) {
        reject(new Error("Recorder not started."));
        return;
      }
      this.mediaRecorder.onstop = async () => {
        try {
          const finalMime = this.mediaRecorder.mimeType || this.getSupportedMimeType() || "audio/webm";
          const ext = this.getExtensionFromMimeType(finalMime);
          const finalBlob = new Blob(this.audioChunks, { type: finalMime });
          this.recordedBlobs.push(finalBlob);
          const files = [];
          if (saveToVault) {
            const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
            const cleanFolder = targetFolder.trim();
            if (cleanFolder !== "") {
              const folderExists = this.app.vault.getFolderByPath(cleanFolder);
              if (!folderExists) {
                await this.app.vault.createFolder(cleanFolder);
              }
            }
            const prefix = cleanFolder !== "" ? `${cleanFolder}/` : "";
            for (let i = 0; i < this.recordedBlobs.length; i++) {
              const suffix = this.recordedBlobs.length > 1 ? `-part${i + 1}` : "";
              const fileName = `Recording-${timestamp}${suffix}.${ext}`;
              const filePath = `${prefix}${fileName}`;
              const arrayBuffer = await this.recordedBlobs[i].arrayBuffer();
              const file = await this.app.vault.createBinary(filePath, arrayBuffer);
              files.push(file);
            }
          }
          const blobs = [...this.recordedBlobs];
          this.cleanup();
          resolve({
            files,
            blobs,
            mimeType: finalMime,
            duration: this.duration
          });
        } catch (e) {
          this.cleanup();
          reject(e);
        }
      };
      this.mediaRecorder.stop();
    });
  }
  cancel() {
    if (this.mediaRecorder && this.mediaRecorder.state !== "inactive") {
      this.mediaRecorder.onstop = () => {
      };
      this.mediaRecorder.stop();
    }
    this.cleanup();
  }
  cleanup() {
    if (this.timerInterval) {
      clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
      this.stream = null;
    }
    this.mediaRecorder = null;
    this.audioChunks = [];
    this.recordedBlobs = [];
    this.isRecording = false;
    this.isPaused = false;
    this.duration = 0;
    this.onStateChange({ isRecording: this.isRecording, isPaused: this.isPaused });
  }
};

// src/api.ts
var import_obsidian = require("obsidian");
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + chunk)));
  }
  return window.btoa(binary);
}
var UnifiedApiClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Helper to resolve the correct Whisper API endpoint with robust path checking
   */
  getWhisperUrl() {
    let endpoint = this.settings.apiUrl.trim();
    endpoint = endpoint.replace(/\/+$/, "");
    if (!endpoint.includes("/audio/transcriptions")) {
      endpoint = endpoint + "/audio/transcriptions";
    }
    return endpoint;
  }
  /**
   * Helper to manually build a multipart/form-data payload for requestUrl
   */
  buildMultipartBody(fileBuffer, fileName, mimeType, fields) {
    const boundary = "----ObsidianBoundary" + Math.random().toString(36).substring(2);
    const enc = new TextEncoder();
    const parts = [];
    for (const [key, value] of Object.entries(fields)) {
      if (value === void 0 || value === null || value === "")
        continue;
      const fieldHeader = `--${boundary}\r
Content-Disposition: form-data; name="${key}"\r
\r
${value}\r
`;
      parts.push(enc.encode(fieldHeader).buffer);
    }
    const fileHeader = `--${boundary}\r
Content-Disposition: form-data; name="file"; filename="${fileName}"\r
Content-Type: ${mimeType}\r
\r
`;
    parts.push(enc.encode(fileHeader).buffer);
    parts.push(fileBuffer);
    const closing = `\r
--${boundary}--\r
`;
    parts.push(enc.encode(closing).buffer);
    const totalLength = parts.reduce((acc, part) => acc + part.byteLength, 0);
    const combined = new Uint8Array(totalLength);
    let offset = 0;
    for (const part of parts) {
      combined.set(new Uint8Array(part), offset);
      offset += part.byteLength;
    }
    return {
      body: combined.buffer,
      contentType: `multipart/form-data; boundary=${boundary}`
    };
  }
  /**
   * Transcribe a single audio chunk via Whisper
   */
  async transcribeChunk(fileBuffer, mimeType, index) {
    const whisperKey = this.settings.whisperApiKey;
    if (!whisperKey) {
      throw new Error("Whisper API key is missing.");
    }
    const endpoint = this.getWhisperUrl();
    const ext = mimeType.includes("webm") ? "webm" : mimeType.includes("ogg") ? "ogg" : mimeType.includes("mp4") || mimeType.includes("aac") ? "m4a" : mimeType.includes("mpeg") ? "mp3" : "webm";
    const fileName = `chunk-${index}-${Date.now()}.${ext}`;
    const fields = {
      model: this.settings.model,
      temperature: this.settings.temperature.toString(),
      response_format: this.settings.responseFormat
    };
    if (this.settings.language) {
      fields.language = this.settings.language;
    }
    if (this.settings.prompt) {
      fields.prompt = this.settings.prompt;
    }
    const { body, contentType } = this.buildMultipartBody(fileBuffer, fileName, mimeType, fields);
    const params = {
      url: endpoint,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${whisperKey}`,
        "Content-Type": contentType
      },
      body
    };
    if (this.settings.debugMode) {
      console.log(`[Whisper Debug] Sending chunk ${index + 1} to ${endpoint} with filename ${fileName} (MIME: ${mimeType})`);
    }
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`Status ${response.status}: ${response.text}`);
      }
      if (this.settings.responseFormat.includes("json")) {
        const json = response.json;
        if (json && json.text !== void 0) {
          return json.text;
        }
      }
      return response.text.trim();
    } catch (error) {
      const errMessage = error.message || JSON.stringify(error);
      throw new Error(`Whisper Transcription failed for model '${this.settings.model}' at URL '${endpoint}'. Details: ${errMessage}`);
    }
  }
  /**
   * Transcribe a single audio chunk via Google Gemini API (inlineData)
   */
  async transcribeGemini(fileBuffer, mimeType, index) {
    const apiKey = this.settings.geminiApiKey;
    if (!apiKey) {
      throw new Error("Gemini API key is missing. Required for Gemini audio transcription.");
    }
    const base64Data = arrayBufferToBase64(fileBuffer);
    const model = this.settings.geminiTranscriptionModel || "gemini-2.5-flash";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const promptText = "Please transcribe this audio verbatim. Keep all speaker dialog, fix no spelling, and return only the transcript content, nothing else.";
    const params = {
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: promptText
              },
              {
                inlineData: {
                  mimeType: mimeType || "audio/webm",
                  data: base64Data
                }
              }
            ]
          }
        ]
      })
    };
    if (this.settings.debugMode) {
      console.log(`[Gemini Debug] Transcribing chunk ${index + 1} via Gemini Model ${model} (MIME: ${mimeType})`);
    }
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`Status ${response.status}: ${response.text}`);
      }
      const json = response.json;
      if (json && json.candidates && json.candidates[0] && json.candidates[0].content && json.candidates[0].content.parts && json.candidates[0].content.parts[0] && json.candidates[0].content.parts[0].text) {
        return json.candidates[0].content.parts[0].text.trim();
      }
      throw new Error("Unexpected response format from Gemini API during transcription");
    } catch (error) {
      const errMessage = error.message || JSON.stringify(error);
      throw new Error(`Gemini transcription failed for model '${model}'. Details: ${errMessage}`);
    }
  }
  /**
   * Post-process a transcribed string using the selected LLM provider
   */
  async postProcess(text, prompt) {
    const provider = this.settings.postProcessingProvider;
    if (this.settings.debugMode) {
      console.log(`[Whisper Debug] Post-processing transcript with ${provider} using model ${this.settings.postProcessingModel}`);
    }
    switch (provider) {
      case "anthropic":
        return this.callAnthropic(text, prompt);
      case "openai":
        return this.callOpenAI(text, prompt);
      case "gemini":
        return this.callGemini(text, prompt);
      default:
        throw new Error(`Unknown post-processing provider: ${provider}`);
    }
  }
  /**
   * Generate a title from the transcript
   */
  async generateTitle(text) {
    const titlePrompt = this.settings.titlePrompt || "Generate a short title (1-5 words) for the following text. Return only the title, nothing else.";
    try {
      const generated = await this.postProcess(text, titlePrompt);
      return generated.replace(/["'’.]/g, "").trim();
    } catch (e) {
      console.warn("Failed to generate title, using fallback", e);
      return "";
    }
  }
  async callAnthropic(text, systemPrompt) {
    const apiKey = this.settings.anthropicApiKey;
    if (!apiKey) {
      throw new Error("Anthropic API key is missing.");
    }
    const url = "https://api.anthropic.com/v1/messages";
    const params = {
      url,
      method: "POST",
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
      },
      body: JSON.stringify({
        model: this.settings.postProcessingModel || "claude-3-5-haiku-20241022",
        max_tokens: 4096,
        messages: [
          {
            role: "user",
            content: `${systemPrompt}

Transcription:
${text}`
          }
        ]
      })
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`Status ${response.status}: ${response.text}`);
      }
      const json = response.json;
      if (json && json.content && json.content[0] && json.content[0].text) {
        return json.content[0].text.trim();
      }
      throw new Error("Unexpected response format from Anthropic API");
    } catch (error) {
      const errMessage = error.message || JSON.stringify(error);
      throw new Error(`Anthropic post-processing failed for model '${this.settings.postProcessingModel}' at URL '${url}'. Details: ${errMessage}`);
    }
  }
  async callOpenAI(text, systemPrompt) {
    const apiKey = this.settings.openaiApiKey;
    if (!apiKey) {
      throw new Error("OpenAI API key is missing.");
    }
    const url = "https://api.openai.com/v1/chat/completions";
    const params = {
      url,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: this.settings.postProcessingModel || "gpt-4o-mini",
        messages: [
          {
            role: "user",
            content: `${systemPrompt}

Transcription:
${text}`
          }
        ]
      })
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`Status ${response.status}: ${response.text}`);
      }
      const json = response.json;
      if (json && json.choices && json.choices[0] && json.choices[0].message && json.choices[0].message.content) {
        return json.choices[0].message.content.trim();
      }
      throw new Error("Unexpected response format from OpenAI API");
    } catch (error) {
      const errMessage = error.message || JSON.stringify(error);
      throw new Error(`OpenAI post-processing failed for model '${this.settings.postProcessingModel}' at URL '${url}'. Details: ${errMessage}`);
    }
  }
  async callGemini(text, systemPrompt) {
    const apiKey = this.settings.geminiApiKey;
    if (!apiKey) {
      throw new Error("Gemini API key is missing.");
    }
    const model = this.settings.postProcessingModel || "gemini-2.5-flash";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const params = {
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}

Transcription:
${text}`
              }
            ]
          }
        ]
      })
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`Status ${response.status}: ${response.text}`);
      }
      const json = response.json;
      if (json && json.candidates && json.candidates[0] && json.candidates[0].content && json.candidates[0].content.parts && json.candidates[0].content.parts[0] && json.candidates[0].content.parts[0].text) {
        return json.candidates[0].content.parts[0].text.trim();
      }
      throw new Error("Unexpected response format from Gemini API");
    } catch (error) {
      const errMessage = error.message || JSON.stringify(error);
      throw new Error(`Gemini post-processing failed for model '${model}' at URL '${url}'. Details: ${errMessage}`);
    }
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  whisperApiKey: "",
  openaiApiKey: "",
  anthropicApiKey: "",
  geminiApiKey: "",
  transcriptionProvider: "openai",
  geminiTranscriptionModel: "gemini-2.5-flash",
  apiUrl: "https://api.openai.com/v1",
  model: "whisper-1",
  language: "",
  prompt: "",
  temperature: 0,
  responseFormat: "json",
  selectedMic: "default",
  saveAudioFile: true,
  audioFolder: "Recordings",
  createNoteFile: true,
  noteFolder: "Meetings",
  noteFilenameTemplate: "{{datetime}}",
  noteTemplate: "![[{{audioFile}}]]\n{{transcription}}",
  autoInsertLink: true,
  promptOnSave: false,
  enablePostProcessing: true,
  postProcessingProvider: "anthropic",
  postProcessingModel: "claude-3-5-haiku-20241022",
  postProcessingPrompt: 'You are a transcription editor. Clean up the following voice transcription: fix grammar, remove filler words (um, uh, like) and repetitions, and improve readability. Format the text in markdown. If there are action items or to-dos, format them as task lists with "[ ]". Preserve the original meaning and language. Return only the polished text, nothing else.',
  autoGenerateTitle: true,
  titlePrompt: "Generate a short title (1-5 words) for the following text. Return only the title, nothing else.",
  keepOriginalTranscription: false,
  debugMode: false
};
var WhisperAudioSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  async display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "API Keys" });
    new import_obsidian2.Setting(containerEl).setName("Whisper API Key").setDesc("API key for Whisper transcription (OpenAI, Groq, or Azure)").addText(
      (text) => text.setPlaceholder("Enter Whisper API key").setValue(this.plugin.settings.whisperApiKey).onChange(async (value) => {
        this.plugin.settings.whisperApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("OpenAI API Key").setDesc("API key for GPT post-processing models").addText(
      (text) => text.setPlaceholder("Enter OpenAI API key").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Anthropic API Key").setDesc("API key for Claude post-processing models").addText(
      (text) => text.setPlaceholder("Enter Anthropic API key").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
        this.plugin.settings.anthropicApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Gemini API Key").setDesc("API key for Gemini transcription and post-processing").addText(
      (text) => text.setPlaceholder("Enter Gemini API key").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
        this.plugin.settings.geminiApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Transcription" });
    new import_obsidian2.Setting(containerEl).setName("Transcription Provider").setDesc("Select whether to use OpenAI Whisper or Google Gemini for audio transcription").addDropdown(
      (dropdown) => dropdown.addOption("openai", "OpenAI Whisper").addOption("gemini", "Google Gemini").setValue(this.plugin.settings.transcriptionProvider).onChange(async (value) => {
        this.plugin.settings.transcriptionProvider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.transcriptionProvider === "openai") {
      new import_obsidian2.Setting(containerEl).setName("API URL").setDesc("Specify the endpoint that will be used to make requests to (e.g. OpenAI or Groq compatibility)").addText(
        (text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
          this.plugin.settings.apiUrl = value.trim();
          await this.plugin.saveSettings();
        })
      );
      const modelOptions = {
        "whisper-1": "whisper-1 (OpenAI)",
        "whisper-large-v3": "whisper-large-v3 (Groq)",
        "whisper-large-v3-turbo": "whisper-large-v3-turbo (Groq)",
        "custom": "Custom Model ID"
      };
      const currentModel = this.plugin.settings.model;
      const isCustomModel = !["whisper-1", "whisper-large-v3", "whisper-large-v3-turbo"].includes(currentModel);
      new import_obsidian2.Setting(containerEl).setName("Model").setDesc("Select the transcription model (or choose Custom to enter your own)").addDropdown((dropdown) => {
        dropdown.addOptions(modelOptions).setValue(isCustomModel ? "custom" : currentModel).onChange(async (value) => {
          if (value === "custom") {
            if (!isCustomModel) {
              this.plugin.settings.model = "";
            }
          } else {
            this.plugin.settings.model = value;
          }
          await this.plugin.saveSettings();
          this.display();
        });
      });
      if (isCustomModel) {
        new import_obsidian2.Setting(containerEl).setName("Custom Model ID").setDesc("Enter custom Whisper-compatible model ID").addText(
          (text) => text.setPlaceholder("e.g., whisper-1").setValue(this.plugin.settings.model).onChange(async (value) => {
            this.plugin.settings.model = value.trim();
            await this.plugin.saveSettings();
          })
        );
      }
      new import_obsidian2.Setting(containerEl).setName("Language").setDesc("Specify the language, or leave empty for auto-detection (e.g. en)").addText(
        (text) => text.setPlaceholder("en (leave empty for auto)").setValue(this.plugin.settings.language).onChange(async (value) => {
          this.plugin.settings.language = value.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Prompt").setDesc("Optional: Add words with their correct spellings to help with transcription.").addText(
        (text) => text.setPlaceholder("Example: ZyntriQix, Digi").setValue(this.plugin.settings.prompt).onChange(async (value) => {
          this.plugin.settings.prompt = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Temperature").setDesc("Sampling temperature (0 to 1). Higher values produce more random output.").addText(
        (text) => text.setPlaceholder("0").setValue(this.plugin.settings.temperature.toString()).onChange(async (value) => {
          const parsed = parseFloat(value);
          this.plugin.settings.temperature = isNaN(parsed) ? 0 : parsed;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Response format").setDesc("Output format: json, text, srt, verbose_json, or vtt").addDropdown(
        (dropdown) => dropdown.addOption("json", "json").addOption("text", "text").addOption("verbose_json", "verbose_json").setValue(this.plugin.settings.responseFormat).onChange(async (value) => {
          this.plugin.settings.responseFormat = value;
          await this.plugin.saveSettings();
        })
      );
    } else {
      const geminiModels = {
        "gemini-2.5-flash": "gemini-2.5-flash (Google Gemini)",
        "gemini-2.5-pro": "gemini-2.5-pro (Google Gemini)",
        "gemini-3.5-flash": "gemini-3.5-flash (Google Gemini)",
        "gemini-3.1-flash-lite": "gemini-3.1-flash-lite (Google Gemini)",
        "custom": "Custom Model ID"
      };
      const currentGeminiModel = this.plugin.settings.geminiTranscriptionModel || "gemini-2.5-flash";
      const isCustomGemini = !["gemini-2.5-flash", "gemini-2.5-pro", "gemini-3.5-flash", "gemini-3.1-flash-lite"].includes(currentGeminiModel);
      new import_obsidian2.Setting(containerEl).setName("Gemini Model").setDesc("Select the Gemini model to transcribe your audio").addDropdown((dropdown) => {
        dropdown.addOptions(geminiModels).setValue(isCustomGemini ? "custom" : currentGeminiModel).onChange(async (value) => {
          if (value === "custom") {
            if (!isCustomGemini) {
              this.plugin.settings.geminiTranscriptionModel = "";
            }
          } else {
            this.plugin.settings.geminiTranscriptionModel = value;
          }
          await this.plugin.saveSettings();
          this.display();
        });
      });
      if (isCustomGemini) {
        new import_obsidian2.Setting(containerEl).setName("Custom Gemini Model ID").setDesc("Enter custom Gemini model ID").addText(
          (text) => text.setPlaceholder("e.g., gemini-2.5-flash").setValue(this.plugin.settings.geminiTranscriptionModel).onChange(async (value) => {
            this.plugin.settings.geminiTranscriptionModel = value.trim();
            await this.plugin.saveSettings();
          })
        );
      }
    }
    containerEl.createEl("h2", { text: "Recording" });
    const micSetting = new import_obsidian2.Setting(containerEl).setName("Microphone").setDesc("Select the audio input device to use for recording");
    try {
      const devices = await navigator.mediaDevices.enumerateDevices();
      const audioMics = devices.filter((d) => d.kind === "audioinput");
      micSetting.addDropdown((dropdown) => {
        dropdown.addOption("default", "Default Microphone");
        for (const mic of audioMics) {
          if (mic.deviceId) {
            dropdown.addOption(mic.deviceId, mic.label || `Microphone (${mic.deviceId.slice(0, 5)})`);
          }
        }
        dropdown.setValue(this.plugin.settings.selectedMic);
        dropdown.onChange(async (value) => {
          this.plugin.settings.selectedMic = value;
          await this.plugin.saveSettings();
        });
      });
    } catch (e) {
      micSetting.addDropdown((dropdown) => {
        dropdown.addOption("default", "Default Microphone");
        dropdown.setValue("default");
      });
    }
    new import_obsidian2.Setting(containerEl).setName("Save audio file").setDesc("Save the audio recording to the vault").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.saveAudioFile).onChange(async (value) => {
        this.plugin.settings.saveAudioFile = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.saveAudioFile) {
      new import_obsidian2.Setting(containerEl).setName("Audio save path").setDesc("Folder in the vault where audio files are saved").addText(
        (text) => text.setPlaceholder("Example: folder/audio").setValue(this.plugin.settings.audioFolder).onChange(async (value) => {
          this.plugin.settings.audioFolder = value.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h2", { text: "Output" });
    new import_obsidian2.Setting(containerEl).setName("Create note file").setDesc("Create a new note file for each transcription (if disabled, inserts directly at current cursor position)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.createNoteFile).onChange(async (value) => {
        this.plugin.settings.createNoteFile = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.createNoteFile) {
      new import_obsidian2.Setting(containerEl).setName("Note save path").setDesc("Folder in the vault where note files are saved").addText(
        (text) => text.setPlaceholder("Example: folder/note").setValue(this.plugin.settings.noteFolder).onChange(async (value) => {
          this.plugin.settings.noteFolder = value.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Note filename template").setDesc("Template for note filenames. Variables: {{date}}, {{time}}, {{datetime}}, {{title}}").addText(
        (text) => text.setPlaceholder("{{datetime}}").setValue(this.plugin.settings.noteFilenameTemplate).onChange(async (value) => {
          this.plugin.settings.noteFilenameTemplate = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Note template").setDesc("Template for note content. Variables: {{transcription}}, {{audioFile}}, {{date}}, {{time}}, {{datetime}}, {{title}}. Use ![[{{audioFile}}]] to embed or [[{{audioFile}}]] to link.").addTextArea(
        (text) => text.setPlaceholder("![[{{audioFile}}]]\n{{transcription}}").setValue(this.plugin.settings.noteTemplate).onChange(async (value) => {
          this.plugin.settings.noteTemplate = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Auto-Insert Link").setDesc("Automatically insert a link to the generated meeting note in your active file at the cursor position.").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.autoInsertLink).onChange(async (value) => {
          this.plugin.settings.autoInsertLink = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Prompt on save").setDesc("Display a popup to customize the folder and filename before saving the note file.").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.promptOnSave).onChange(async (value) => {
          this.plugin.settings.promptOnSave = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h2", { text: "Post-processing" });
    new import_obsidian2.Setting(containerEl).setName("Enable post-processing").setDesc("Clean up transcriptions with an LLM \u2014 fix grammar, remove filler words, improve readability").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enablePostProcessing).onChange(async (value) => {
        this.plugin.settings.enablePostProcessing = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enablePostProcessing) {
      new import_obsidian2.Setting(containerEl).setName("Provider").setDesc("Select the LLM provider to clean up your note (Anthropic and OpenAI use API keys set above)").addDropdown(
        (dropdown) => dropdown.addOption("anthropic", "Anthropic").addOption("openai", "OpenAI").addOption("gemini", "Gemini").setValue(this.plugin.settings.postProcessingProvider).onChange(async (value) => {
          this.plugin.settings.postProcessingProvider = value;
          if (value === "anthropic") {
            this.plugin.settings.postProcessingModel = "claude-3-5-haiku-20241022";
          } else if (value === "openai") {
            this.plugin.settings.postProcessingModel = "gpt-4o-mini";
          } else if (value === "gemini") {
            this.plugin.settings.postProcessingModel = "gemini-2.5-flash";
          }
          await this.plugin.saveSettings();
          this.display();
        })
      );
      let recommendedModels = {};
      let defaultModel = "";
      const provider = this.plugin.settings.postProcessingProvider;
      if (provider === "anthropic") {
        recommendedModels = {
          "claude-3-5-haiku-20241022": "claude-3-5-haiku (Anthropic)",
          "claude-3-5-sonnet-20241022": "claude-3-5-sonnet (Anthropic)",
          "custom": "Custom Model ID"
        };
        defaultModel = "claude-3-5-haiku-20241022";
      } else if (provider === "openai") {
        recommendedModels = {
          "gpt-4o-mini": "gpt-4o-mini (OpenAI)",
          "gpt-4o": "gpt-4o (OpenAI)",
          "custom": "Custom Model ID"
        };
        defaultModel = "gpt-4o-mini";
      } else if (provider === "gemini") {
        recommendedModels = {
          "gemini-2.5-flash": "gemini-2.5-flash (Google Gemini)",
          "gemini-2.5-pro": "gemini-2.5-pro (Google Gemini)",
          "gemini-3.5-flash": "gemini-3.5-flash (Google Gemini)",
          "gemini-3.1-flash-lite": "gemini-3.1-flash-lite (Google Gemini)",
          "custom": "Custom Model ID"
        };
        defaultModel = "gemini-2.5-flash";
      }
      const currentPPModel = this.plugin.settings.postProcessingModel || defaultModel;
      const isCustomPP = !Object.keys(recommendedModels).filter((k) => k !== "custom").includes(currentPPModel);
      new import_obsidian2.Setting(containerEl).setName("Post-processing model").setDesc("Select the model for post-processing").addDropdown((dropdown) => {
        dropdown.addOptions(recommendedModels).setValue(isCustomPP ? "custom" : currentPPModel).onChange(async (value) => {
          if (value === "custom") {
            if (!isCustomPP) {
              this.plugin.settings.postProcessingModel = "";
            }
          } else {
            this.plugin.settings.postProcessingModel = value;
          }
          await this.plugin.saveSettings();
          this.display();
        });
      });
      if (isCustomPP) {
        new import_obsidian2.Setting(containerEl).setName("Custom Post-processing Model ID").setDesc("Enter custom model ID").addText(
          (text) => text.setPlaceholder(`e.g., ${defaultModel}`).setValue(this.plugin.settings.postProcessingModel).onChange(async (value) => {
            this.plugin.settings.postProcessingModel = value.trim();
            await this.plugin.saveSettings();
          })
        );
      }
      new import_obsidian2.Setting(containerEl).setName("Post-processing prompt").setDesc("Instructions for the LLM on how to clean up the transcription").addTextArea(
        (text) => text.setPlaceholder("Enter prompt...").setValue(this.plugin.settings.postProcessingPrompt).onChange(async (value) => {
          this.plugin.settings.postProcessingPrompt = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("Auto-generate title").setDesc("Use the LLM to generate a descriptive filename/title for notes").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.autoGenerateTitle).onChange(async (value) => {
          this.plugin.settings.autoGenerateTitle = value;
          await this.plugin.saveSettings();
          this.display();
        })
      );
      if (this.plugin.settings.autoGenerateTitle) {
        new import_obsidian2.Setting(containerEl).setName("Title generation prompt").setDesc("Instructions for the LLM on how to generate the title").addTextArea(
          (text) => text.setPlaceholder("Generate a short title...").setValue(this.plugin.settings.titlePrompt).onChange(async (value) => {
            this.plugin.settings.titlePrompt = value;
            await this.plugin.saveSettings();
          })
        );
      }
      new import_obsidian2.Setting(containerEl).setName("Keep original transcription").setDesc("Append the raw Whisper transcription below the post-processed text").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.keepOriginalTranscription).onChange(async (value) => {
          this.plugin.settings.keepOriginalTranscription = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h2", { text: "Advanced" });
    new import_obsidian2.Setting(containerEl).setName("Debug mode").setDesc("Increase the plugin's verbosity for troubleshooting").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
        this.plugin.settings.debugMode = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var WhisperAudioPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.activeModal = null;
  }
  async onload() {
    await this.loadSettings();
    this.recorder = new AudioRecorder(this.app);
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar(0, false);
    this.recorder.onTick = (duration) => {
      this.updateStatusBar(duration, true);
      if (this.activeModal) {
        this.activeModal.updateTimer(duration);
      }
    };
    this.recorder.onStateChange = (state) => {
      if (!state.isRecording) {
        this.updateStatusBar(0, false);
      }
      if (this.activeModal) {
        this.activeModal.updateControls();
      }
    };
    this.addRibbonIcon("microphone", "AI Audio Transcription and Summary", () => {
      this.openRecorderModal();
    });
    this.addCommand({
      id: "open-recorder",
      name: "Open AI Recorder Controls",
      callback: () => this.openRecorderModal()
    });
    this.addCommand({
      id: "start-recording",
      name: "Start Audio Recording",
      checkCallback: (checking) => {
        if (!this.recorder.isRecording) {
          if (!checking) {
            const maxChunkSize = this.settings.transcriptionProvider === "gemini" ? 10 * 1024 * 1024 : 22 * 1024 * 1024;
            this.recorder.start(this.settings.selectedMic, maxChunkSize).then(() => {
              new import_obsidian3.Notice("Audio recording started...");
            }).catch((err) => {
              new import_obsidian3.Notice("Failed to start recording: " + err.message);
            });
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "stop-recording",
      name: "Stop and Process Audio",
      checkCallback: (checking) => {
        if (this.recorder.isRecording) {
          if (!checking) {
            this.handleStopAndProcess();
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new WhisperAudioSettingTab(this.app, this));
  }
  onunload() {
    if (this.recorder.isRecording) {
      this.recorder.cancel();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    let needsMigration = false;
    if (this.settings.geminiTranscriptionModel === "gemini-1.5-flash" || this.settings.geminiTranscriptionModel === "gemini-2.0-flash") {
      this.settings.geminiTranscriptionModel = "gemini-2.5-flash";
      needsMigration = true;
    } else if (this.settings.geminiTranscriptionModel === "gemini-1.5-pro") {
      this.settings.geminiTranscriptionModel = "gemini-2.5-pro";
      needsMigration = true;
    }
    if (this.settings.postProcessingModel === "gemini-1.5-flash" || this.settings.postProcessingModel === "gemini-2.0-flash") {
      this.settings.postProcessingModel = "gemini-2.5-flash";
      needsMigration = true;
    } else if (this.settings.postProcessingModel === "gemini-1.5-pro") {
      this.settings.postProcessingModel = "gemini-2.5-pro";
      needsMigration = true;
    }
    if (this.settings.model === "gemini-1.5-flash" || this.settings.model === "gemini-2.0-flash") {
      this.settings.model = "gemini-2.5-flash";
      needsMigration = true;
    } else if (this.settings.model === "gemini-1.5-pro") {
      this.settings.model = "gemini-2.5-pro";
      needsMigration = true;
    }
    if (needsMigration) {
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openRecorderModal() {
    if (this.activeModal) {
      this.activeModal.open();
      return;
    }
    this.activeModal = new RecorderModal(this.app, this);
    this.activeModal.onClose = () => {
      this.activeModal = null;
    };
    this.activeModal.open();
  }
  updateStatusBar(seconds, isRecording) {
    if (!this.statusBarItem)
      return;
    if (isRecording) {
      const minutes = Math.floor(seconds / 60);
      const secs = seconds % 60;
      const timeStr = `${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
      this.statusBarItem.setText(`\u{1F399}\uFE0F Recording: ${timeStr}`);
      this.statusBarItem.className = "gemini-status-bar-recording";
      this.statusBarItem.onclick = () => this.openRecorderModal();
    } else {
      this.statusBarItem.setText("");
      this.statusBarItem.className = "";
      this.statusBarItem.onclick = null;
    }
  }
  async handleStopAndProcess() {
    let needsWhisperKey = this.settings.transcriptionProvider === "openai" && !this.settings.whisperApiKey;
    let needsGeminiKey = (this.settings.transcriptionProvider === "gemini" || this.settings.postProcessingProvider === "gemini") && !this.settings.geminiApiKey;
    let needsProviderKey = false;
    let providerName = "";
    if (this.settings.enablePostProcessing) {
      const provider = this.settings.postProcessingProvider;
      if (provider === "anthropic" && !this.settings.anthropicApiKey) {
        needsProviderKey = true;
        providerName = "anthropic";
      } else if (provider === "openai" && !this.settings.openaiApiKey) {
        needsProviderKey = true;
        providerName = "openai";
      } else if (provider === "gemini" && !this.settings.geminiApiKey) {
        needsGeminiKey = true;
      }
    }
    if (needsWhisperKey || needsGeminiKey || needsProviderKey) {
      const promptModal = new ApiKeyPromptModal(this.app, this, needsWhisperKey, needsGeminiKey, providerName);
      promptModal.open();
      const confirmed = await promptModal.promise();
      if (!confirmed) {
        new import_obsidian3.Notice("Processing cancelled due to missing API keys.");
        this.recorder.cancel();
        return;
      }
    }
    const notice = new import_obsidian3.Notice("Finalizing recording...", 0);
    try {
      const result = await this.recorder.stop(this.settings.audioFolder, this.settings.saveAudioFile);
      if (this.settings.saveAudioFile) {
        const filePaths = result.files.map((f) => f.path).join(", ");
        new import_obsidian3.Notice(`Audio saved locally: ${filePaths}`);
      }
      await this.processRecordedChunks(result, notice);
    } catch (error) {
      console.error(error);
      new import_obsidian3.Notice("Recording stop failed: " + error.message);
      notice.hide();
    }
  }
  async processRecordedChunks(result, notice) {
    try {
      const client = new UnifiedApiClient(this.settings);
      let fullTranscription = "";
      let transcriptionErrors = [];
      for (let i = 0; i < result.blobs.length; i++) {
        const blob = result.blobs[i];
        if (blob.size < 1024) {
          if (this.settings.debugMode) {
            console.log(`[Transcription Debug] Skipping chunk ${i + 1} because size is too small (${blob.size} bytes).`);
          }
          continue;
        }
        try {
          const arrayBuffer = await blob.arrayBuffer();
          notice.setMessage(`Transcribing audio part ${i + 1} of ${result.blobs.length} using ${this.settings.transcriptionProvider}...`);
          let textSegment = "";
          if (this.settings.transcriptionProvider === "gemini") {
            textSegment = await client.transcribeGemini(arrayBuffer, result.mimeType, i);
          } else {
            textSegment = await client.transcribeChunk(arrayBuffer, result.mimeType, i);
          }
          if (textSegment && textSegment.trim()) {
            fullTranscription += (fullTranscription ? " " : "") + textSegment.trim();
          }
        } catch (err) {
          const errMsg = err.message || String(err);
          console.error(`Failed to transcribe chunk ${i + 1}:`, err);
          transcriptionErrors.push(`Part ${i + 1}: ${errMsg}`);
          new import_obsidian3.Notice(`Warning: Failed to transcribe audio part ${i + 1}. Skipping this segment.`, 5e3);
        }
      }
      if (!fullTranscription.trim()) {
        const errorText = transcriptionErrors.length > 0 ? `Transcription failed:
${transcriptionErrors.map((e) => `- ${e}`).join("\n")}` : "All audio chunks were empty or too small to transcribe.";
        if (this.settings.createNoteFile) {
          notice.setMessage("Creating fallback note...");
          const fallbackContent = `> [!WARNING] Transcription Failed
> ${errorText.replace(/\n/g, "\n> ")}

The audio recording has been saved to your vault.

` + (result.files.length > 0 ? result.files.map((f) => `![[${f.path}]]`).join("\n") : "");
          await this.createMeetingNote(result, "", "", fallbackContent, "Failed Transcription");
          new import_obsidian3.Notice("Transcription failed, but your audio file was saved and linked in a new note.", 1e4);
        } else {
          new import_obsidian3.Notice(`Error: ${errorText}`, 1e4);
        }
        return;
      }
      let finalOutput = fullTranscription;
      let polishedText = "";
      if (this.settings.enablePostProcessing && fullTranscription.trim()) {
        notice.setMessage(`Cleaning up transcription using ${this.settings.postProcessingProvider}...`);
        try {
          polishedText = await client.postProcess(fullTranscription, this.settings.postProcessingPrompt);
          if (this.settings.keepOriginalTranscription) {
            finalOutput = `${polishedText}

### Original Transcript
${fullTranscription}`;
          } else {
            finalOutput = polishedText;
          }
        } catch (err) {
          const ppError = err.message || String(err);
          console.error("Post-processing failed:", err);
          new import_obsidian3.Notice(`Warning: Post-processing failed. Using raw transcription.`, 8e3);
          finalOutput = `> [!WARNING] Post-processing Failed
> ${ppError.replace(/\n/g, "\n> ")}

${fullTranscription}`;
        }
      }
      if (transcriptionErrors.length > 0) {
        finalOutput = `> [!WARNING] Some audio parts failed to transcribe:
` + transcriptionErrors.map((e) => `> - ${e}`).join("\n") + `

` + finalOutput;
      }
      if (this.settings.createNoteFile) {
        notice.setMessage("Creating new note file...");
        let title = "";
        if (this.settings.enablePostProcessing && this.settings.autoGenerateTitle && fullTranscription.trim()) {
          notice.setMessage("Generating note title...");
          try {
            title = await client.generateTitle(polishedText || fullTranscription);
          } catch (err) {
            console.error("Title generation failed:", err);
          }
        }
        await this.createMeetingNote(result, fullTranscription, polishedText, finalOutput, title);
      } else {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (activeView && activeView.editor) {
          activeView.editor.replaceSelection(finalOutput);
          new import_obsidian3.Notice("Transcription pasted at cursor.");
        } else {
          new import_obsidian3.Notice("Error: No active Markdown editor found to paste transcription.");
        }
      }
    } catch (error) {
      console.error(error);
      new import_obsidian3.Notice("API processing failed: " + error.message, 1e4);
    } finally {
      notice.hide();
    }
  }
  async createMeetingNote(result, rawTranscript, polishedTranscript, processedOutput, generatedTitle) {
    const date = /* @__PURE__ */ new Date();
    const dateStr = date.toISOString().split("T")[0];
    const timeStr = date.toTimeString().split(" ")[0].replace(/:/g, "-");
    const datetimeStr = `${dateStr} ${date.toTimeString().split(" ")[0]}`;
    const titleVal = generatedTitle.trim() || `Meeting-${dateStr}-${timeStr}`;
    let noteTemplate = this.settings.noteTemplate;
    const audioFileRegex = /(!?\s*\[+\s*)?\{\{audioFile\}\}(\s*\]+\s*)?/g;
    if (this.settings.saveAudioFile && result.files.length > 0) {
      noteTemplate = noteTemplate.replace(audioFileRegex, (match, prefix, suffix) => {
        if (prefix && prefix.trim().startsWith("!")) {
          return result.files.map((f) => `![[${f.path}]]`).join("\n");
        } else if (prefix) {
          return result.files.map((f) => `[[${f.path}]]`).join("\n");
        } else {
          return result.files.map((f) => f.path).join("\n");
        }
      });
    } else {
      noteTemplate = noteTemplate.replace(audioFileRegex, "");
    }
    const templateVariables = {
      transcription: processedOutput,
      date: dateStr,
      time: date.toTimeString().split(" ")[0],
      datetime: datetimeStr,
      title: titleVal
    };
    const noteContent = this.resolveTemplate(noteTemplate, templateVariables);
    const rawFilename = this.resolveTemplate(this.settings.noteFilenameTemplate, templateVariables);
    let cleanFilename = rawFilename.replace(/[\\\/:\*\?"<>\|]/g, "-").trim() || `Meeting-${dateStr}-${timeStr}`;
    let targetNoteFolder = this.settings.noteFolder.trim();
    if (this.settings.promptOnSave) {
      const saveModal = new SaveNoteModal(this.app, targetNoteFolder, cleanFilename);
      saveModal.open();
      const choice = await saveModal.promise();
      if (!choice) {
        await navigator.clipboard.writeText(noteContent);
        new import_obsidian3.Notice("Save cancelled. Transcription/Summary copied to clipboard.", 1e4);
        return;
      }
      targetNoteFolder = choice.folder.trim();
      cleanFilename = choice.filename.replace(/[\\\/:\*\?"<>\|]/g, "-").trim() || `Meeting-${dateStr}-${timeStr}`;
    }
    const noteName = `${cleanFilename}.md`;
    if (targetNoteFolder !== "") {
      const folderExists = this.app.vault.getFolderByPath(targetNoteFolder);
      if (!folderExists) {
        await this.app.vault.createFolder(targetNoteFolder);
      }
    }
    const folderPrefix = targetNoteFolder !== "" ? `${targetNoteFolder}/` : "";
    const notePath = `${folderPrefix}${noteName}`;
    const noteFile = await this.app.vault.create(notePath, noteContent);
    new import_obsidian3.Notice(`Success! Created meeting note: ${notePath}`, 5e3);
    if (this.settings.autoInsertLink) {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (activeView && activeView.editor) {
        const link = `[[${noteFile.path}|Meeting - ${titleVal}]]`;
        activeView.editor.replaceSelection(link);
      }
    }
    await this.app.workspace.getLeaf().openFile(noteFile);
  }
  resolveTemplate(template, vars) {
    let result = template;
    for (const [key, value] of Object.entries(vars)) {
      result = result.split(`{{${key}}}`).join(value);
    }
    return result;
  }
};
var ApiKeyPromptModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, needsWhisper, needsGemini, providerName) {
    super(app);
    this.plugin = plugin;
    this.needsWhisper = needsWhisper;
    this.needsGemini = needsGemini;
    this.providerName = providerName;
    this.whisperKeyInput = "";
    this.geminiKeyInput = "";
    this.providerKeyInput = "";
  }
  promise() {
    return new Promise((resolve) => {
      this.resolvePromise = resolve;
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.titleEl.setText("AI Transcription & Summary - Missing Keys");
    const descriptionEl = contentEl.createEl("p", {
      text: "To transcribe and process your audio, please enter the missing API keys below. They will be saved to your plugin settings."
    });
    descriptionEl.style.marginBottom = "20px";
    if (this.needsWhisper) {
      new import_obsidian3.Setting(contentEl).setName("Whisper API Key").setDesc("Required for audio transcription via OpenAI Whisper.").addText(
        (text) => text.setPlaceholder("Enter Whisper API key").onChange((val) => {
          this.whisperKeyInput = val.trim();
        })
      );
    }
    if (this.needsGemini) {
      new import_obsidian3.Setting(contentEl).setName("Gemini API Key").setDesc("Required for Gemini transcription and/or post-processing.").addText(
        (text) => text.setPlaceholder("Enter Gemini API key").onChange((val) => {
          this.geminiKeyInput = val.trim();
        })
      );
    }
    if (this.providerName && this.providerName !== "gemini") {
      const name = this.providerName.charAt(0).toUpperCase() + this.providerName.slice(1);
      new import_obsidian3.Setting(contentEl).setName(`${name} API Key`).setDesc(`Required for LLM post-processing using ${name}.`).addText(
        (text) => text.setPlaceholder(`Enter ${name} API key`).onChange((val) => {
          this.providerKeyInput = val.trim();
        })
      );
    }
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save & Continue").setCta().onClick(async () => {
        if (this.needsWhisper && this.whisperKeyInput) {
          this.plugin.settings.whisperApiKey = this.whisperKeyInput;
        }
        if (this.needsGemini && this.geminiKeyInput) {
          this.plugin.settings.geminiApiKey = this.geminiKeyInput;
        }
        if (this.providerName && this.providerKeyInput) {
          if (this.plugin.settings.postProcessingProvider === "anthropic") {
            this.plugin.settings.anthropicApiKey = this.providerKeyInput;
          } else if (this.plugin.settings.postProcessingProvider === "openai") {
            this.plugin.settings.openaiApiKey = this.providerKeyInput;
          }
        }
        await this.plugin.saveSettings();
        this.resolvePromise(true);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.resolvePromise(false);
        this.close();
      })
    );
  }
  onClose() {
    this.resolvePromise(false);
  }
};
var RecorderModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.titleEl.setText("AI Audio Recorder");
    const container = contentEl.createDiv({ cls: "gemini-recorder-modal" });
    this.timerEl = container.createEl("div", {
      cls: "gemini-recorder-timer",
      text: this.formatTime(this.plugin.recorder.duration)
    });
    this.statusEl = container.createEl("div", {
      cls: "gemini-recorder-status",
      text: this.getStatusText()
    });
    this.visualizerEl = container.createDiv({ cls: "gemini-recorder-visualizer" });
    for (let i = 0; i < 15; i++) {
      this.visualizerEl.createDiv({ cls: "gemini-recorder-wave-bar" });
    }
    this.controlsEl = container.createDiv({ cls: "gemini-recorder-controls" });
    this.updateControls();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  updateTimer(seconds) {
    if (this.timerEl) {
      this.timerEl.setText(this.formatTime(seconds));
    }
  }
  getStatusText() {
    const recorder = this.plugin.recorder;
    if (!recorder.isRecording)
      return "Ready to record";
    if (recorder.isPaused)
      return "Recording paused";
    return "Recording audio...";
  }
  updateControls() {
    if (!this.controlsEl)
      return;
    this.controlsEl.empty();
    const recorder = this.plugin.recorder;
    if (this.visualizerEl) {
      if (recorder.isRecording && !recorder.isPaused) {
        this.visualizerEl.classList.add("recording");
      } else {
        this.visualizerEl.classList.remove("recording");
      }
    }
    if (this.statusEl) {
      this.statusEl.setText(this.getStatusText());
    }
    if (!recorder.isRecording) {
      const recordBtn = this.controlsEl.createEl("button", {
        cls: "gemini-recorder-btn gemini-recorder-btn-record",
        text: "\u{1F399}\uFE0F Start Recording"
      });
      recordBtn.onclick = async () => {
        try {
          const maxChunkSize = this.plugin.settings.transcriptionProvider === "gemini" ? 10 * 1024 * 1024 : 22 * 1024 * 1024;
          await recorder.start(this.plugin.settings.selectedMic, maxChunkSize);
          this.updateControls();
        } catch (e) {
          new import_obsidian3.Notice("Error accessing microphone: " + e.message);
        }
      };
    } else {
      if (recorder.isPaused) {
        const resumeBtn = this.controlsEl.createEl("button", {
          cls: "gemini-recorder-btn gemini-recorder-btn-pause",
          text: "\u25B6\uFE0F Resume"
        });
        resumeBtn.onclick = () => {
          recorder.resume();
          this.updateControls();
        };
      } else {
        const pauseBtn = this.controlsEl.createEl("button", {
          cls: "gemini-recorder-btn gemini-recorder-btn-pause",
          text: "\u23F8\uFE0F Pause"
        });
        pauseBtn.onclick = () => {
          recorder.pause();
          this.updateControls();
        };
      }
      const stopBtn = this.controlsEl.createEl("button", {
        cls: "gemini-recorder-btn gemini-recorder-btn-stop",
        text: "\u2705 Stop & Transcribe"
      });
      stopBtn.onclick = () => {
        this.close();
        this.plugin.handleStopAndProcess();
      };
      const cancelBtn = this.controlsEl.createEl("button", {
        cls: "gemini-recorder-btn gemini-recorder-btn-cancel",
        text: "\u274C Cancel"
      });
      cancelBtn.onclick = () => {
        if (confirm("Are you sure you want to cancel? This will delete the current recording.")) {
          recorder.cancel();
          this.updateControls();
          this.updateTimer(0);
          new import_obsidian3.Notice("Recording discarded.");
        }
      };
    }
  }
  formatTime(seconds) {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
};
var SaveNoteModal = class extends import_obsidian3.Modal {
  constructor(app, defaultFolder, defaultFilename) {
    super(app);
    this.folder = "";
    this.filename = "";
    this.folder = defaultFolder;
    this.filename = defaultFilename.endsWith(".md") ? defaultFilename.slice(0, -3) : defaultFilename;
  }
  promise() {
    return new Promise((resolve) => {
      this.resolvePromise = resolve;
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.titleEl.setText("File Meeting Note");
    contentEl.createEl("p", { text: "Choose the folder and filename where this meeting note will be saved." });
    new import_obsidian3.Setting(contentEl).setName("Folder path").setDesc("Select or type the destination folder in your vault").addText((text) => {
      text.setValue(this.folder).onChange((value) => {
        this.folder = value.trim();
      });
      const datalistId = "vault-folders-datalist";
      let datalist = document.getElementById(datalistId);
      if (!datalist) {
        datalist = document.body.createEl("datalist");
        datalist.id = datalistId;
        const allFolders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian3.TFolder).map((f) => f.path);
        datalist.createEl("option", { value: "/" });
        for (const fPath of allFolders) {
          datalist.createEl("option", { value: fPath });
        }
      }
      text.inputEl.setAttribute("list", datalistId);
      text.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).setName("Filename").setDesc("Enter the filename (without extension)").addText((text) => {
      text.setValue(this.filename).onChange((value) => {
        this.filename = value.trim();
      });
      text.inputEl.style.width = "100%";
    });
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "10px";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel", cls: "mod-cancel" });
    const saveBtn = buttonContainer.createEl("button", { text: "Save Note", cls: "mod-cta" });
    cancelBtn.onclick = () => {
      this.close();
      this.resolvePromise(null);
    };
    saveBtn.onclick = () => {
      this.close();
      this.resolvePromise({
        folder: this.folder,
        filename: this.filename
      });
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
